### ISSUE TITLE
Struct duplicacy in webservice templates

### ISSUE THREAD

**Issue by shubham-asati** [gophers-prop/golang-appgen#26]
there are two structs for user in forms/user.go and models/user.go. is it necessary to have multiple structs ? 
 This will create confusion for someone who will be using tamplate code for first time.

**Comment by occamist** [comment]
Suggestion: Rename forms folder to dto(data transfer objects) and create 2 more subfolders for request/response then user.go should be renamed as userPostRequest.go or userPostResponse.go.  For the sake of consistency, ,make package names singular. Controller folder should only have userController.go or UserController.go. Model folder can be renamed as Entity to avoid confusion between dto which can be referred as models. Entity folder can have user.go or User.go for the readability and avoiding confusions for beginners

**Comment by shubham-asati** [comment]
this is kind of handled in https://github.com/gophers-prop/golang-appgen/pull/28 . It is good to have request , response models defined but as to keep the template code simpler we don't need to use such patter.
