### ISSUE TITLE
Remove github org name hardcoding

### ISSUE THREAD

**Issue by rajeshdeshpande02** [gophers-prop/golang-appgen#33]
**Describe the bug**
Explore functionality creates a repo in the GitHub organization. But the Name of that Github organization is hardcoded to 'gophers-prop'. 

**To Reproduce**
1. Go to 'http://golangapps.com'
2. Click on 'Select type and package for application'
3. Enter  ' application name'
4. Click on 'Explore' button
5. Check repo is created on 'gophers-prop' which is hardcoded

**Expected behavior**
Github org name should be taken from the environment variable.

**Comment by fuzzmz** [comment]
@rajeshdeshpande02 , tried looking into the code to see under which env var the github organization name is exposed, but couldn't find anything (or looking in the wrong places). What is the environment variable associated with the github org name?

**Comment by snehaljoshi0904** [comment]
@fuzzmz Github organization name(i.e. gophers-prop) is hardcoded in createRepo function(line no: 334 and 381 ) of https://github.com/gophers-prop/golang-appgen/blob/master/handler/handler.go file.
Please assume "GITHUB_ORG_NAME" as env variable name for organization  and replace with hardcoded name.
